### ISSUE TITLE
qsub command line incompatible with PBS Pro

### ISSUE THREAD

**Issue by ptrebert** [mrvollger/SDA#13]
Hi Mitchell,

the below way of constructing the `qsub` call is not compatible with PBS Pro, which only supports the non-default values `oe` and `eo` for merging stdout/stderr (`-j`):

https://github.com/mrvollger/SDA/blob/1fbe948f3d8cde6ae6b8c49b33f4220053755718/SDA#L119

Best,
Peter

**Comment by mrvollger** [comment]
Hi Peter, 

Sorry about this issue, should have foreseen this one. I will get on a fix as soon as I have time. In the mean time if you are in a rush you could just change the way log is setup on that one line for your cluster as I don't think it will be used anywhere else. 

Best,
Mitchell

**Comment by SergejN** [comment]
Hi @mrvollger 
to follow up on that, I also had to modify the script (starting at line 118 of SDA) in order to make it work with SLURM:

```
	elif( args.cluster ):
		if 'sbatch' in args.cluster:
			cmd += f' --cluster " {args.cluster} --output {LOG} " '
		else:
			cmd += f' --cluster " {args.cluster} -j y -o {LOG} " '
```

Best
Sergej

**Comment by SergejN** [comment]
I'm sorry, I just realized that the outputs are not written. The correct code for SLURM should be
```
elif( args.cluster ):
	if 'sbatch' in args.cluster:
		cmd += f' --cluster " {args.cluster} --output {LOG}/slurm-%j.out --error {LOG}/slurm-%j.err " '
	else:
		cmd += f' --cluster " {args.cluster} -j y -o {LOG} " '
```
