### ISSUE TITLE
BAM as expected ONT input

### ISSUE THREAD

**Issue by SergejN** [mrvollger/SDA#15]
Dear @mrvollger ,

sorry if I misunderstood, but from the code (https://github.com/mrvollger/SDA/blob/1fbe948f3d8cde6ae6b8c49b33f4220053755718/SDA.smk#L110), it looks like the rule `minimap2` expects the Nanopore data to be in a BAM file, which is not necessarily the case. The simplest (although admittedly not necessarily the most reliable) would be to look at the extension and differentiate between `*.fq/*.fastq`, `*.fq.gz/*.fastq.gz` and `bam/sam`.  
My nanopore reads are stored as *.fastq.gz, therefore, I had to remove `samtools fasta ...` to make the pipeline work.

thanks!
Sergej

**Comment by mrvollger** [comment]
Thanks for pointing out these mistakes! I will make commits for this and you other comment this evening!
