### ISSUE TITLE
SDA error Repeatmasker no result and pbmm2 

### ISSUE THREAD

**Issue by LILIHAN-001** [mrvollger/SDA#20]
Hi,
I met two issue when I worked the denovo_SDA.smk.
Input : Four scaffold (each length: about 100kb ) 

The fisrt one is No repetitive sequences detected in some Scaffold ( There were no repetitive sequences detected in sda_out/common_repeats/sda.ref.2.fasta) when running Repatmasker and the missing of tbl file interrupted the snakemake.
![image](https://user-images.githubusercontent.com/73207687/111938961-10a14080-8b06-11eb-8916-f35354eb201d.png)
so I added the command and I want to say if it will casuse any new question for the following.
![image](https://user-images.githubusercontent.com/73207687/111937334-77245f80-8b02-11eb-8e5e-a0553d2d00f1.png)

The another question is pbmm2 reported the error "Input is aligned reads. Only primary alignments will be respected to allow idempotence!", but the error won't be occur when we replaced the bam file by fasta file. Do you have any suggestions to that?
![image](https://user-images.githubusercontent.com/73207687/111938472-02065980-8b05-11eb-9efe-f83ea5999f76.png)

Thanks!

**Comment by mrvollger** [comment]
Hi, 

Thanks for the comments!

I just pushed a change that should resolve your repeat masker problem, but if you have a functioning fix on your end you can keep that. 

`pbmm2` is maintained by PacBio and without the data I cannot determine where this error is coming form, sorry. My guess is that there is some issue with your input bam but I am unsure. This message is just a warning and it does not impact `SDA` in any way:
```Input is aligned reads. Only primary alignments will be respected to allow idempotence!```
However I do not know why the following lines have `ERROR`. 

Cheers!
Mitchell

**Comment by LILIHAN-001** [comment]
Hi,

Many thanks for your quickly reply!

The input bam we provided is obtained by minimap2 when we run the denovo_SDA.smk. Now we tried to map PB reads to the genome with pbmm2, pbmm2 in SDA can work nicely and no error be reported. Maybe we lose some informative when align with minimap2. I  suggest that you could notice the requirements of the input bam more clearly. 

thanks
