### ISSUE TITLE
What are the real dependencies for this software

### ISSUE THREAD

**Issue by foriin** [mrvollger/SDA#21]
Hi,
I'm having a trouble understanding why there are 'module' commands in env_sda.sh, though you wrote that there is only requirement for SDA, that is anaconda. I don't have it installed, nor etc/profile.d.modules.sh file. Do I have to install Modules? What other software prerequisites should be there? Could you possibly clear this out?

**Comment by mrvollger** [comment]
SDA is no longer maintained and should not be used. SDA was designed for low quality PacBio (CLR) and ONT long reads, both of which are now substantially higher quality allowing standard assembly tools like Flye, HiCanu, and hifiasm to outperform any results previously possible with SDA. We have added this information to the top of the README and I apologize for not noting this sooner.
