### ISSUE TITLE
Question on readToSNVList

### ISSUE THREAD

**Issue by Lqh09** [mrvollger/SDA#23]
Hi,

I attempted to find the "readToSNVList" file in the "externalRepos/pbgreedyphase/" directory. Do you have any idea where I can find the "readToSNVList" file?

Thank you!
Iris

**Comment by mrvollger** [comment]
SDA is no longer maintained and should not be used. SDA was designed for low quality PacBio (CLR) and ONT long reads, both of which are now substantially higher quality allowing standard assembly tools like Flye, HiCanu, and hifiasm to outperform any results previously possible with SDA. We have added this information to the top of the README and I apologize for not noting this sooner.
