### ISSUE TITLE
AmbiguousRuleException: Rules MapToDups and MapToRef

### ISSUE THREAD

**Issue by MichelMoser** [mrvollger/SDA#5]
Dear SDA developers, 

When running the test dataset, i dont get expected outputs from any assemblers. 
Is that normal behaviour?  

Regarding your readme, i would expect some output like canu.assembly.fasta

```
[Tue Jan 15 10:05:37 2019]
Finished job 3.
16 of 3 steps (533%) done

[Tue Jan 15 10:05:37 2019]
localrule all:
    input: CC/mi.cuts.gml.pdf, group.4.vcf, group.2.vcf, group.0.vcf, group.5.vcf, group.1.vcf, group.3.vcf, Coverage.png, snvs/depth.tsv                                                                                                        jobid: 17

[Tue Jan 15 10:05:37 2019]
Finished job 17.
17 of 3 steps (567%) done
Complete log: /net/fs-1/home01/michelmo/tools/SDA/TestCases/SDAtest/.snakemake/log/2019-01-15T100131.717510.snakemake.log
Building DAG of jobs...
AmbiguousRuleException:
Rules MapToDups and MapToRef are ambiguous for the file asms/canu.dup.bam.
Consider starting rule output with a unique prefix or constrain your wildcards.
Wildcards:
        MapToDups: ASM=canu
        MapToRef: ASM=canu.dup
Expected input files:
        MapToDups: canu.assemblies.fasta duplications.fasta
        MapToRef: canu.dup.assemblies.fasta ref.fasta
                                                           

```

config.json: 

```
{
        "MINCOV" : 27,
        "MAXCOV" : 54,
        "MINTOTAL" : 83,

        "asm" : "/net/eichler/vol2/home/mvollger/assemblies/Mitchell_CHM1_V3/internalassmbly/CHM1.fasta",
        "reads" : "/net/eichler/vol2/home/mvollger/assemblies/CHM1/reads.2017.fofn",
        "project": "CHM1_V4",
        "bax_per_job" : 15,
        "assemble" : "wtdbg"
}


```

Or do i miss some config options and dependencies?
Could you maybe post a complete set of config options?

Thank you, 
Michel

**Comment by mrvollger** [comment]
Hmm I do not get an:
AmbiguousRuleException
when I run. 

Can you please provide the complete output (stdout and stderr), and also your snakemake version. Preferably uploaded as a file.

**Comment by minnndy** [comment]
I have the same problem.
I ran a test database and same problem happened.
So, I'll attach the  output (stdout and stderr) file.
[out.txt](https://github.com/mvollger/SDA/files/2790699/out.txt)

Thank you,
Michel

**Comment by mrvollger** [comment]
This helps thank you. I will start working on a fix. 

Can you also tell me your snakemake version?

Thanks!

**Comment by mrvollger** [comment]
I am using snakemake version 5.2.2 and was unable to recreate your issue. 

Commit 1b1e6ab1c9fd4f081758513503a22dd4c35c0cb5 adds a wildcard constraint that should fix your issue; however, since I cannot test it I do not know for sure.
